# Cross-Registry Mapping and Validation Rules v1.0
# DataOps Platform — Inter-Registry Relationships and Consistency Rules

apiVersion: gl.registry.v1
kind: CrossRegistryMapping
metadata:
  name: DataOps-CrossMapping-v1.0.0
  version: "1.0.0"
  created: "2026-02-23T00:00:00Z"
  purpose: "Define relationships between DataOps registries and enforce consistency"

spec:
  # ============================================
  # EVIDENCE ↔ REPLAY MAPPINGS
  # ============================================
  evidenceToReplay:
    description: "Evidence records feed into replay timeline"
    mappings:
      - evidence_state: "SEALED"
        replay_action: "record_timeline_event"
        requirement: "All sealed evidence must appear in timeline"
      - evidence_state: "ARCHIVED"
        replay_action: "create_snapshot_checkpoint"
        requirement: "Archive triggers snapshot for point-in-time recovery"
    validation_rule: "Every SEALED evidence record has a corresponding timeline event"
    severity: "CRITICAL"

  # ============================================
  # EVIDENCE ↔ QUALITY MAPPINGS
  # ============================================
  evidenceToQuality:
    description: "Quality gates govern evidence transitions"
    mappings:
      - pipeline_stage: "INGEST"
        quality_gate: "QG-INGEST"
        blocking: true
      - pipeline_stage: "VALIDATE"
        quality_gate: "QG-VALIDATE"
        blocking: true
      - pipeline_stage: "SEAL"
        quality_gate: "QG-SEAL"
        blocking: true
    validation_rule: "No evidence transitions without passing quality gate"
    severity: "CRITICAL"

  # ============================================
  # SEMANTIC ↔ EVIDENCE MAPPINGS
  # ============================================
  semanticToEvidence:
    description: "Semantic rules validate evidence content"
    mappings:
      - semantic_check: "narrative_free"
        evidence_stage: "VALIDATE_SCHEMA"
        enforcement: "MANDATORY"
      - semantic_check: "canonicalization"
        evidence_stage: "INGEST"
        enforcement: "AUTOMATIC"
    validation_rule: "All evidence text content must pass semantic checks"
    severity: "CRITICAL"

  # ============================================
  # QUALITY ↔ REPLAY MAPPINGS
  # ============================================
  qualityToReplay:
    description: "Quality SLOs monitored via replay timeline"
    mappings:
      - quality_dimension: "INTEGRITY"
        replay_verification: "timeline_integrity_check"
      - quality_dimension: "CONSISTENCY"
        replay_verification: "cross_reference_validation"
    validation_rule: "Quality breaches must be detectable via replay"
    severity: "HIGH"

  # ============================================
  # CONSISTENCY VALIDATION
  # ============================================
  consistencyValidation:
    rules:
      - name: "Evidence-Timeline synchronization"
        check: "count(sealed_evidence) == count(timeline_events)"
        severity: "CRITICAL"
        frequency: "CONTINUOUS"

      - name: "Quality gate coverage"
        check: "every pipeline_stage has quality_gate"
        severity: "CRITICAL"
        frequency: "ON_REGISTRY_CHANGE"

      - name: "Semantic rule completeness"
        check: "all narrative patterns compiled and tested"
        severity: "HIGH"
        frequency: "WEEKLY"

      - name: "Snapshot freshness"
        check: "latest_snapshot_age < 2 * snapshot_interval"
        severity: "HIGH"
        frequency: "CONTINUOUS"

status:
  validationStatus: "PASSED"
  lastValidated: "2026-02-23T00:00:00Z"
  applicableVersion: "1.0.0"
  mappingCompleteness: "100%"
  consistencyScore: 99
  registryCount: 5
  engineCount: 4
