# =============================================================================
# SecCompOps Platform — External Dependencies Declaration
# =============================================================================
# CRITICAL: This platform has ZERO cross-platform dependencies.
# All dependencies listed here are EXTERNAL only.
apiVersion: gl.platform.v1
kind: DependencyManifest
metadata:
  name: seccompops-platform-dependencies
  version: "1.0.0"

spec:
  cross_platform_dependencies: []  # NONE — fully decoupled

  external_dependencies:
    runtime:
      - name: python
        version: ">=3.11"
        type: language_runtime

      - name: postgresql
        version: ">=16"
        type: database
        purpose: "Audit metadata, evidence storage, compliance records"

      - name: redis
        version: ">=7"
        type: cache
        purpose: "Session management, task queue, pub/sub"

    python_packages:
      core:
        - fastapi
        - uvicorn
        - pydantic
        - sqlalchemy
        - asyncpg
        - redis
        - cryptography
        - pyjwt
        - prometheus-client
        - structlog

    infrastructure:
      - name: docker
        version: ">=24"
        type: container_runtime

      - name: kubernetes
        version: ">=1.28"
        type: orchestration
        optional: true

      - name: helm
        version: ">=3.14"
        type: package_manager
        optional: true
