---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-smoke
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-smoke:sha256-a80d12daf01135e1f849c1ffa3e9f41ab8c2687b0331bd7674a6a296ab6b1abe
  labels:
    app.kubernetes.io/name: performance-benchmark
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    environment: production
    test-type: smoke
  name: performance-benchmark-smoke
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Starting smoke test at $(date)"

              k6 run --out json=/results/smoke-test.json /tests/health-check.js

              echo "Smoke test completed at $(date)"

              '
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: health-check.js
                path: health-check.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-load
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-load:sha256-42e6d4b57bc61d6154efa8c7fa2ca8af1ed6f6bd6e9e38b25b895dc5af100750
  labels:
    app.kubernetes.io/name: performance-benchmark
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    environment: production
    test-type: load
  name: performance-benchmark-load
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Starting load test at $(date)"

              k6 run --out json=/results/load-test.json /tests/api-load-test.js

              echo "Load test completed at $(date)"

              '
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: api-load-test.js
                path: api-load-test.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-stress
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-stress:sha256-3540d5b39d1cc414cb02815890a3bb39d1612ba2be1546b0c5670c026f92bcfe
  labels:
    app.kubernetes.io/name: performance-benchmark
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    environment: production
    test-type: stress
  name: performance-benchmark-stress
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Starting stress test at $(date)"

              k6 run --out json=/results/stress-test.json /tests/stress-test.js

              echo "Stress test completed at $(date)"

              '
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 2000m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: stress-test.js
                path: stress-test.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: 0 2 * * *
  successfulJobsHistoryLimit: 2
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-endurance
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-endurance:sha256-35ff6f08102ad88e1ece55b171fecde27c587b9243e0a75ca143fa0e35218b04
  labels:
    app.kubernetes.io/name: performance-benchmark
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    environment: production
    test-type: endurance
  name: performance-benchmark-endurance
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c - | echo "Starting endurance test at $(date)" k6 run --out json=/results/endurance-test.json
              /tests/memory-leak-test.js echo "Endurance test completed at $(date)"
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: memory-leak-test.js
                path: memory-leak-test.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: 0 0 * * 0
  successfulJobsHistoryLimit: 1
