---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-smoke
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-smoke:sha256-c8c28855f95bb14598990a145a1ae494c62858be18de220ce129d5c48e6cd546
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: performance-benchmark
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    environment: production
    test-type: smoke
  name: performance-benchmark-smoke
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Starting smoke test at $(date)"

              k6 run --out json=/results/smoke-test.json /tests/health-check.js

              echo "Smoke test completed at $(date)"

              '
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: health-check.js
                path: health-check.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-load
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-load:sha256-f4b823feefaf85a7657c927c0d735fbb55ac50d5a18f654b3c12ee4a8056ab9e
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: performance-benchmark
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    environment: production
    test-type: load
  name: performance-benchmark-load
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Starting load test at $(date)"

              k6 run --out json=/results/load-test.json /tests/api-load-test.js

              echo "Load test completed at $(date)"

              '
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: api-load-test.js
                path: api-load-test.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-stress
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-stress:sha256-2b8ff162d7818460853798a88d6e7077087362eff1975f015d96dc64a5dea295
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: performance-benchmark
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    environment: production
    test-type: stress
  name: performance-benchmark-stress
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - 'echo "Starting stress test at $(date)"

              k6 run --out json=/results/stress-test.json /tests/stress-test.js

              echo "Stress test completed at $(date)"

              '
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 2000m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: stress-test.js
                path: stress-test.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: 0 2 * * *
  successfulJobsHistoryLimit: 2
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/cronjob/performance-benchmark-endurance
    eco-base/urn: urn:eco-base:k8s:core:cronjob:performance-benchmark-endurance:sha256-14256f1bde1950b0ca3ea33612293d00b282caa9cdfcd37c4924311201d916c0
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: performance-benchmark
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    environment: production
    test-type: endurance
  name: performance-benchmark-endurance
  namespace: production
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c - | echo "Starting endurance test at $(date)" k6 run --out json=/results/endurance-test.json
              /tests/memory-leak-test.js echo "Endurance test completed at $(date)"
            image: grafana/k6:latest
            name: k6
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
            - mountPath: /tests
              name: k6-tests
            - mountPath: /results
              name: results
          restartPolicy: OnFailure
          volumes:
          - configMap:
              items:
              - key: memory-leak-test.js
                path: memory-leak-test.js
              name: k6-tests
            name: k6-tests
          - emptyDir: {}
            name: results
  schedule: 0 0 * * 0
  successfulJobsHistoryLimit: 1
