# Loki Logging Stack Configuration
# P0 Critical: Centralized logging with Loki, Promtail, and Grafana

---
# Loki Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: superai-platform
    component: loki
spec:
  serviceName: loki-headless
  replicas: 1
  selector:
    matchLabels:
      app: superai-platform
      component: loki
  template:
    metadata:
      labels:
        app: superai-platform
        component: loki
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3100"
    spec:
      serviceAccountName: superai-monitoring
      containers:
      - name: loki
        image: grafana/loki:2.9.2
        args:
          - -config.file=/etc/loki/local-config.yaml
          - -table-manager.retention-periods=72h
        ports:
        - name: http-metrics
          containerPort: 3100
        - name: grpc
          containerPort: 9096
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /loki
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
  labels:
    app: superai-platform
    component: loki
data:
  local-config.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    
    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    
    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100
    
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_entries_limit_per_query: 5000
      split_queries_by_interval: 30m
    
    ruler:
      alertmanager_url: http://alertmanager.default.svc.cluster.local:9093
      
      # Security-specific alert rules
      rules:
        - alert: SecurityEventDetected
          expr: |
            sum(rate({namespace="default", container=~".*"} |~ "Security|Attack|Breach|Compromise" [5m])) by (container, namespace)
          for: 1m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Security event detected in {{ $labels.container }}"
          
        - alert: HighErrorRate
          expr: |
            sum(rate({namespace="default", level="error"}[5m])) by (container) > 0.1
          for: 5m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "High error rate in {{ $labels.container }}"
          
        - alert: ContainerCrashLoop
          expr: |
            sum(rate({namespace="default"} |~ "CrashLoopBackOff|Error:.*failed" [5m])) by (pod) > 0
          for: 1m
          labels:
            severity: critical
            team: ops
          annotations:
            summary: "Container {{ $labels.pod }} is crash looping"
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: superai-platform
    component: loki
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 3100
    targetPort: http-metrics
  - name: grpc
    port: 9096
    targetPort: grpc
  selector:
    app: superai-platform
    component: loki
---
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  namespace: monitoring
  labels:
    app: superai-platform
    component: loki
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 3100
    targetPort: http-metrics
  selector:
    app: superai-platform
    component: loki
---
# Promtail Deployment
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: superai-platform
    component: promtail
spec:
  selector:
    matchLabels:
      app: superai-platform
      component: promtail
  template:
    metadata:
      labels:
        app: superai-platform
        component: promtail
    spec:
      serviceAccountName: superai-monitoring
      containers:
      - name: promtail
        image: grafana/promtail:2.9.2
        args:
          - -config.file=/etc/promtail/config.yml
          - -client.url=http://loki:3100/loki/api/v1/push
        ports:
        - name: http-metrics
          containerPort: 3101
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
        - name: containers
          mountPath: /var/log/containers
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker/containers
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
      volumes:
      - name: config
        configMap:
          name: promtail-config
      - name: pods
        hostPath:
          path: /var/log/pods
      - name: containers
        hostPath:
          path: /var/log/containers
      - name: docker
        hostPath:
          path: /var/lib/docker/containers
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
  labels:
    app: superai-platform
    component: promtail
data:
  config.yml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0
    
    clients:
      - url: http://loki:3100/loki/api/v1/push
    
    scrape_configs:
      # SuperAI Platform Application Logs
      - job_name: superai-platform
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: superai-platform
            action: keep
          - source_labels: [__meta_kubernetes_pod_label_component]
            target_label: component
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
            target_label: __path__
      
      # System Logs
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*.log
      
      # Kubernetes Events
      - job_name: kubernetes-events
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: superai-platform
            action: keep
        pipeline_stages:
          - cri: {}
      
      # Security Logs (Falco)
      - job_name: falco
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: falco
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
      
    # Pipeline stages for log processing
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            user: user
            container: container
      - labels:
          level:
          user:
          container:
      - match:
          selector: '{level="error"}'
          action: drop
          drop_counter_reason: "error_logs_dropped"
---
# Loki ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: superai-platform
    component: loki
spec:
  selector:
    matchLabels:
      app: superai-platform
      component: loki
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
---
# Promtail ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: superai-platform
    component: promtail
spec:
  selector:
    matchLabels:
      app: superai-platform
      component: promtail
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
---
# Grafana Datasource for Loki
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false
        editable: true
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: jaeger
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"